### ISSUE TITLE
ImportError: cannot import name adjustFiles

### ISSUE THREAD

**Issue by golharam** [common-workflow-language/cwl2script#2]
I have cwltool installed and can successfully run cwl workflows.  I install cwl2script in the same pyton virtual environment, but when I run cwl2script test/revsort.cwl test/revsort-job.json, I get:

Traceback (most recent call last):
  File "/home/golharr/workspace/common-workflow-language/cwl_venv/bin/cwl2script", line 9, in <module>
    load_entry_point('cwl2script==1.0', 'console_scripts', 'cwl2script')()
  File "/home/golharr/workspace/common-workflow-language/cwl_venv/lib/python2.7/site-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/golharr/workspace/common-workflow-language/cwl_venv/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2570, in load_entry_point
    return ep.load()
  File "/home/golharr/workspace/common-workflow-language/cwl_venv/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2230, in load
    return self.resolve()
  File "/home/golharr/workspace/common-workflow-language/cwl_venv/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2236, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "build/bdist.linux-x86_64/egg/cwl2script.py", line 7, in <module>
ImportError: cannot import name adjustFiles

I'm not sure why this would be.

**Comment by mr-c** [comment]
Hello @golharam and thank you for your issue. This code hasn't been updated in ten months, and the CWL reference implementation has changed its internal API several times since then.
